project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-On Exercises
        menu: 
          - text: Hands-On Exercise 1A
            href: Hands-on_Ex1/Hands-on_Ex1A.html
          - text: Hands-On Exercise 1B
            href: Hands-on_Ex1/Hands-on_Ex1B.html
          - text: Hands-On Exercise 2A
            href: Hands-on_Ex2/Hands-on_Ex2A.html
          - text: Hands-On Exercise 2B
            href: Hands-on_Ex2/Hands-on_Ex2B.html
          - text: Hands-On Exercise 2C
            href: Hands-on_Ex2/Hands-on_Ex2C.html
          - text: Hands-On Exercise 3
            href: Hands-on_Ex3/Hands-on_Ex3.html
            
      - text: In-Class Exercises
        menu: 
          - text: In-Class Exercise 1
            href: In-class_Ex1/In-class_Ex1.html
          - text: In-Class Exercise 2A
            href: In-class_Ex2/In-class_Ex2A.html
          - text: In-Class Exercise 2B
            href: In-class_Ex2/In-class_Ex2B.html
          - text: In-Class Exercise 2C
            href: In-class_Ex2/In-class_Ex2C.html
          - text: In-Class Exercise 3
            href: In-class_Ex3/In-class_Ex3.html
          - text: In-Class Exercise 4A
            href: In-class_Ex4/In-class_Ex4A.html
          - text: In-Class Exercise 4B
            href: In-class_Ex4/In-class_Ex4B.html
          - text: In-Class Exercise 5
            href: In-class_Ex5/In-class_Ex5.html

      - text: Take-Home Exercises
        menu: 
          - text: Take-Home Exercise 1
            href: Take-home_Ex1/Take-home_Ex1.html
            
          - text: Take-Home Exercise 2
            href: Take-home_Ex2/Take-home_Ex2.html
            
    right:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

