project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-On Exercises
        menu: 
          - text: Hands-On Exercise 1A
            href: Hands-on_Ex1/Hands-on_Ex1A.html
          - text: Hands-On Exercise 1B
            href: Hands-on_Ex1/Hands-on_Ex1B.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

